var list = {
            "data":[
                        {
                                "title":"朱七-青春",
                                "src":"http://static.jory.wang/music/folk/朱七-青春.mp3"
                       },
                        {
                                "title":"赵雷-青春无处安放",
                                "src":"http://static.jory.wang/music/folk/赵雷-青春无处安放.mp3"
                       },
                        {
                                "title":"靳松-独自旅行",
                                "src":"http://static.jory.wang/music/folk/靳松-独自旅行.mp3"
                       },
                        {
                                "title":"靳松-老路小路",
                                "src":"http://static.jory.wang/music/folk/靳松-老路小路.mp3"
                       },
                        {
                                "title":"蒋山-怎么办",
                                "src":"http://static.jory.wang/music/folk/蒋山-怎么办.mp3"
                       },
                        {
                                "title":"蒋山-面朝大海春暖花开",
                                "src":"http://static.jory.wang/music/folk/蒋山-面朝大海春暖花开.mp3"
                       },
                        {
                                "title":"蒋山-我干了你随意",
                                "src":"http://static.jory.wang/music/folk/蒋山-我干了你随意.mp3"
                       },
                        {
                                "title":"蒋山-西南小镇",
                                "src":"http://static.jory.wang/music/folk/蒋山-西南小镇.mp3"
                       }
            ]
    };